image: Visual Studio 2017

version: 3.0.0

skip_commits:
  message: /updated? readme.*s/

build: false

install:
  - ps: |
      $null = Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
      Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
      Install-Module Configuration, Pester, InvokeBuild
      Set-Location $env:APPVEYOR_BUILD_FOLDER\$env:APPVEYOR_PROJECT_NAME

build_script:
  - ps: |
      Invoke-Build .\.build.bootstrap.ps1 -Task Build
      Invoke-Build -Task Setup, Build

test_script:
  - ps: |
    Invoke-Build -Task Setup, Test
  - pwsh: |
    Invoke-Build -Task Setup, Test